apiVersion: v1
kind: Service

metadata:
  name: backend-service
  labels:
    app.kubernetes.io/name: rgukt-connect-backend

spec:
  selector:
    app.kubernetes.io/name: rgukt-connect-backend

  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

  type: ClusterIP