pipeline {
    agent any

    stages {
        stage('Build & Package') {
            steps {
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend') {
                    sh 'docker build -t rgukt-connect-backend:latest .'
                }
            }
        }
    }
}
