pipeline {
    agent any

    environment {
        IMAGE_NAME = "rgukt-connect-backend"
        CONTAINER_NAME = "rgukt-connect-backend"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true
                '''
            }
        }

        stage('Run Backend') {
            steps {
                withCredentials([file(credentialsId: 'rgukt-connect-env', variable: 'ENV_FILE')]) {
                    sh '''
                    docker run -d \
                      --name ${CONTAINER_NAME} \
                      --restart unless-stopped \
                      --env-file "$ENV_FILE" \
                      -p 8000:8000 \
                      ${IMAGE_NAME}:latest
                    '''
                }
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                echo "Waiting for application..."
                sleep 15
                curl --fail http://localhost:8000/actuator/health || exit 1
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed x'
        }

        always {
            sh 'docker image prune -f || true'
        }
    }
}