spring.application.name=rgukt-connect

server.port=4000

# ?Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/rgukt_connect
spring.datasource.username=rgukt-backend
spring.datasource.password=Uday@5632


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=rgukt_connect_enterprise_level_secure_jwt_signing_key_2026_string
# Token duration: 1 hour (in milliseconds)
jwt.accessTokenExpiration=3600000
# Token duration: 7 days (in milliseconds)
jwt.refreshTokenExpiration=604800000